repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-added-large-files

  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.1.12
    hooks:
      - id: insert-license
        args: ["--license-file", "docs/license_header.txt"]
        types_or: [python]

  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black

  - repo: https://github.com/pycqa/isort
    rev: 5.11.5
    hooks:
      - id: isort
        args: ["--profile", "black", "--filter-files"]

  - repo: https://github.com/pycqa/flake8
    rev: 5.0.4
    hooks:
      - id: flake8
        args: ["--config=.flake8"]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.981
    hooks:
      - id: mypy
        types: [python]
        exclude: >
          (?x)^(
            src/stretch/perception/detection/detic/Detic|
            src/stretch/app|
            src/stretch_ros2_bridge|
            third_party/|
            src/stretch/agent|
            src/stretch/perception|
            src/stretch/visualization
          )
        args:
          - --ignore-missing-imports
          - --install-types
          - --non-interactive
          - --no-strict-optional
          - --disable-error-code=override
          - --disable-error-code=attr-defined
  - repo: https://github.com/kynan/nbstripout
    rev: 0.6.1
    hooks:
      - id: nbstripout

  # Beautysh formats Bash scripts 
  - repo: https://github.com/lovesegfault/beautysh 
    rev: v6.2.1 
    hooks: 
      - id: beautysh 

  # Mdformat formats Markdown files 
  #- repo: https://github.com/executablebooks/mdformat 
  #  rev: 0.7.16 
  #  hooks: 
  #    - id: mdformat 

  # Codespell checks the code for common misspellings 
  - repo: https://github.com/codespell-project/codespell 
    rev: v2.2.4 
    hooks: 
      - id: codespell 
        args: 
          - --ignore-words=.codespell-ignore-words.txt
        exclude: > 
          (?x)^( 
            | .*\.svg 
            | .*\.tsv
            | ^src/test/audio/test_text_to_speech.py
          )$ 
