CLASS_LABELS_200 =(
    'wall',
    'background',
    'object',
    'range hood',
    'door',
    'stove',
    'bathroom stall',
    'divider',
    'clothes dryer',
    'file cabinet',
    'cabinet',
    'bathroom cabinet',
    'blackboard',
    'curtain',
    'blinds',
    'tv',
    'mattress',
    'bathtub',
    'glass',
    'shower',
    'power outlet',
    'water dispenser',
    'bulletin board',
    'printer',
    'windowsill',
    'bookshelf',
    'dresser',
    'storage organizer',
    'fireplace',
    'fire alarm',
    'piano',
    'shelf',
    'kitchen counter',
    'washing machine',
    'stairs',
    'paper cutter',
    'sink',
    'window',
    'refrigerator',
    'counter',
    'closet',
    'bathroom vanity',
    'radiator',
    'vent',
    'kitchen cabinet',
    'water cooler',
    'doorframe',
    'closet door',
    'table',

    'shower head',
    'spray',
    'inhaler',
    'guitar case',
    'plunger',
    'toilet paper dispenser',
    'adapter',
    'soy sauce',
    'pipe',
    'bottle',
    'scale',
    'paper towel',
    'paper towel roll',
    'scissors',
    'tape',
    'chopsticks',
    'case of water bottles',
    'hand sanitizer',
    'laptop',
    'alcohol disinfection',
    'keyboard',
    'coffee maker',
    'light',
    'toaster',
    'stuffed animal',
    'toilet seat cover dispenser',
    'ironing board',
    'fire extinguisher',
    'fruit',
    'container',
    'bag',
    'oven',
    'body wash',
    'bucket',
    'cd case',
    'tray',
    'bowl',
    'speaker',
    'crate',
    'projector',
    'book',
    'school bag',
    'laundry detergent',
    'clothes',
    'candle',
    'basket',
    'face wash',
    'notebook',
    'purse',
    'trash bin',
    'paper bag',
    'package',
    'disinfecting wipes',
    'recycling bin',
    'headphones',
    'mouse',
    'shower gel',
    'dustpan',
    'cup',
    'vacuum cleaner',
    'dish rack',
    'coffee kettle',
    'plants',
    'rag',
    'can',
    'cushion',
    'monitor',
    'fan',
    'tube',
    'box',
    'ball',
    'bicycle',
    'guitar',
    'trash can',
    'hand sanitizers',
    'paper towel dispenser',
    'whiteboard',
    'bin',
    'potted plant',
    'tennis',
    'soap dish',
    'structure',
    'calendar',
    'dumbbell',
    'fish oil',
    'ottoman',
    'stool',
    'hand wash',
    'lamp',
    'toaster oven',
    'music stand',
    'water bottle',
    'clock',
    'charger',
    'picture',
    'bascketball',
    'microwave',
    'screwdriver',
    'rack',
    'apple',
    'suitcase',
    'ladder',
    'ping pong ball',
    'dishwasher',
    'storage container',
    'toilet paper holder',
    'coat rack',
    'soap dispenser',
    'banana',
    'toilet paper',
    'mug',
    'marker pen',
    'hat',
    'aerosol',
    'luggage',
    'poster',
    'bed',
    'cart',
    'light switch',
    'backpack',
    'power strip',
    'baseball',
    'mustard',
    'water pitcher',
    'couch',
    'beverage',
    'toy',
    'salt',
    'plant',
    'pillow',
    'broom',
    'pepper',
    'muffins',
    'multivitamin',
    'towel',
    'storage bin',
    'nightstand',
    'telephone',
    'tissue box',
    'hair dryer',
    'mirror',
    'sign',
    'plate',
    'tripod',
    'chair',
    'plastic bag',
    'umbrella',
    'paper',
    'laundry hamper',
    'food',
    'jacket',
    'computer tower',
    'keyboard piano',
    'person',
    'machine',
    'projector screen',
    'shoe',
)