FROM dustynv/l4t-text-generation:r35.3.1

# Set up timezone
ENV TZ=UTC
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

# Set a DOCKER flag to indicate we are running in a container
ENV DOCKER 1

# Copy the directory in
COPY . .

RUN ls
